version: 2
registries:
  govuk-once:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PRIVATE_REPO_ACCESS_GITHUB_TOKEN}}
updates:
  - package-ecosystem: uv
    registries: '*'
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
