version: 2
updates:
  - package-ecosystem: uv
    directory: /
    registries: "*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.PRIVATE_REPO_ACCESS_GITHUB_TOKEN }}
