[project]
name = "example-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "agent-runtime-types",
    "aws-opentelemetry-distro>=0.16.0",
    "bedrock-agentcore>=1.4.5",
    "govuk-chat-v2-prototype-private",
    "strands-agents>=1.30.0",
]

[dependency-groups]
dev = [
    "bedrock-agentcore-starter-toolkit>=0.3.9",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pyyaml>=6.0.3",
    "ruff>=0.15.0",
]

[build-system]
requires = ["setuptools>=82.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]

[tool.uv.sources]
govuk-chat-v2-prototype-private = { git = "https://github.com/govuk-once/govuk-chat-v2-prototype-private.git" }
