default_agent: atomicRed_Agent
is_agentcore_create_with_iac: true
agents:
  atomicRed_Agent:
    name: atomicRed_Agent
    entrypoint: /Users/kevin.dew/govuk/govuk-chat-v2-prototype/services/simple-agent/atomicRed/src/main.py
    deployment_type: container
    source_path: /Users/kevin.dew/govuk/govuk-chat-v2-prototype/services/simple-agent/atomicRed/src
    aws:
      account: null
      region: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    is_generated_by_agentcore_create: true
