[project]
name = "chat-assistants"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "anthropic[bedrock]>=0.71.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.20",
]

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]
