[project]
name = "chat-assistants"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "anthropic[bedrock]>=0.71.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.3.0",
    "respx>=0.22.0",
    "ruff>=0.14.1",
]

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]
