[project]
name = "chat-api-serverless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# contrived example dependencies to test bundling
dependencies = [
    "chat-assistants",
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "ruff>=0.13.3",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]
