[project]
name = "chat-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "chat-assistants",
    "fastapi[standard]>=0.118.0",
    "sse-starlette>=3.0.3",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "python-dotenv>=1.1.1",
    "ruff>=0.13.3",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]

[tool.uv.sources]
chat-assistants = { path = "../../libs/python/chat-assistants", editable = true }
