name: CDK CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cdk-ci.yaml"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "cdk/**"
  pull_request:
    paths:
      - ".github/workflows/cdk-ci.yaml"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "cdk/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run tests
        run: cdk/scripts/test.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run linter
        run: cdk/scripts/lint.sh

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run formatter
        run: cdk/scripts/format.sh

  typing:
    name: Type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run type checks
        run: cdk/scripts/type-check.sh
