name: Chat API CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ".github/actions/setup-python-uv-env/*"
      - ".github/workflows/chat-api-ci.yaml"
      - "uv.lock"
      - "services/chat-api/**"
  pull_request:
    paths:
      - ".github/actions/setup-python-uv-env/*"
      - ".github/workflows/chat-api-ci.yaml"
      - "uv.lock"
      - "services/chat-api/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-python-uv-env
        with:
          dependencies_github_token: ${{ secrets.PRIVATE_REPO_ACCESS_GITHUB_TOKEN }}

      - name: Run tests
        run: services/chat-api/scripts/test.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-python-uv-env
        with:
          dependencies_github_token: ${{ secrets.PRIVATE_REPO_ACCESS_GITHUB_TOKEN }}

      - name: Run linter
        run: services/chat-api/scripts/lint.sh

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-python-uv-env
        with:
          dependencies_github_token: ${{ secrets.PRIVATE_REPO_ACCESS_GITHUB_TOKEN }}

      - name: Run formatter
        run: services/chat-api/scripts/format.sh

  typing:
    name: Type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-python-uv-env
        with:
          dependencies_github_token: ${{ secrets.PRIVATE_REPO_ACCESS_GITHUB_TOKEN }}

      - name: Run type checks
        run: services/chat-api/scripts/type-check.sh
