name: Chat UI CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '.github/actions/setup-node-pnpm-env/*'
      - '.github/workflows/chat-ui-ci.yaml'
      - '.dockerignore'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'services/chat-ui/**'
  pull_request:
    paths:
      - '.github/actions/setup-node-pnpm-env/*'
      - '.github/workflows/chat-ui-ci.yaml'
      - '.dockerignore'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'services/chat-ui/**'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run tests
        run: services/chat-ui/scripts/test.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run linter
        run: services/chat-ui/scripts/lint.sh

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run formatter
        run: services/chat-ui/scripts/format.sh

  typing:
    name: Type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run type checks
        run: services/chat-ui/scripts/type-check.sh

  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build image
        run: docker build -f services/chat-ui/Dockerfile -t chat-ui .

      - name: Run container
        run: docker run --detach --name chat-ui --publish 3000:3000 chat-ui

      - name: Check health endpoint
        run: >-
          curl --fail --silent --show-error
          --retry 10 --retry-delay 1 --retry-all-errors
          http://localhost:3000/api/health

      - name: Show container logs
        if: failure()
        run: docker logs chat-ui
