name: Chat Assistants CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "uv.lock"
      - "libs/python/chat-assistants/**"
  pull_request:
    paths:
      - "uv.lock"
      - "libs/python/chat-assistants/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run tests
        run: libs/python/chat-assistants/scripts/test.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run linter
        run: libs/python/chat-assistants/scripts/lint.sh

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run formatter
        run: libs/python/chat-assistants/scripts/format.sh

  typing:
    name: Type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run type checks
        run: libs/python/chat-assistants/scripts/type-check.sh
