name: Chat Prototyping CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "utilities/chat-prototyping/**"
  pull_request:
    paths:
      - "utilities/chat-prototyping/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run tests
        run: utilities/chat-prototyping/scripts/test.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run linter
        run: utilities/chat-prototyping/scripts/lint.sh

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run formatter
        run: utilities/chat-prototyping/scripts/format.sh

  typing:
    name: Type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/setup-python-uv-env

      - name: Run type checks
        run: utilities/chat-prototyping/scripts/type-check.sh
