name: Format Non-Projects CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - 'services/**'
      - 'libs/**'
      - 'utilities/**'
      - 'cdk/**'
  pull_request:
    paths-ignore:
      - 'services/**'
      - 'libs/**'
      - 'utilities/**'
      - 'cdk/**'

jobs:
  prettier_format:
    name: Prettier formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-node-pnpm-env

      - name: Run Prettier
        run: scripts/format-non-projects.sh
